### ISSUE TITLE
[1.20.1][Connector b45][Forge] Crash on Better Combat swing

### ISSUE THREAD

**Issue by Carsonated** [ZsoltMolnarrr/Rogues#14]
[crash-2024-09-09_06.38.37-client.txt](https://github.com/user-attachments/files/16929829/crash-2024-09-09_06.38.37-client.txt)

**Comment by Carsonated** [comment]
Suspected Unionlib incompat, though resetting the configs caused such to work before removing the mod all together

**Comment by ZsoltMolnarrr** [comment]
Thank you for the response. Sorry that I was unable to provide more meaningful help.
