### ISSUE TITLE
Rogue dilemma [Problem/Idea]

### ISSUE THREAD

**Issue by shoverno2** [ZsoltMolnarrr/Rogues#15]
Rogue class, in idea, uses dual knifes or sickles.
However, most of melee attack mobs having enough range to inevitably hit rogue build player on their attempt to attack.

Rogues are fragile and cannot stand much of hits.
Stun skill doesn't helps a lot, 'cause cooldown is quite long for consistent use; +bosses are immune to stun, while creepers exploding even when stunned.
Everything under range of swords is suicide mission.

That class needs some changes.

I thought on that, and right now an idea of possible change came on my mind.

One skill to spare, if 5 skills is not an option.
AoE stun is bit of useful when crowded, teleport to enemy back skill is the only "ranged" option for this class,
vanish skill is great escape plan.
"Slice and dice" is buff, that comes as first skill.
Yes, it has consistancy in usage, but it's just buff.
Though, there's no need to dump it completely.
It could be changed...

Concept:
Skill "Dirty trick" (called "rogue" not for nothing; alternative skill name - "Pocket sand")
is active skill that hit-scans single entity in range of 3.
On hit entity is stunned for 2 seconds, while user gets "Slice and dice" buff for 3 seconds. (Which makes usage of fast attack weapon way more relevant)
Cooldown should be something like 3-5 seconds, so rogue can consistently use this skill in combat, while being able to survive melee mobs.
+ if mob ignores stun effect (bosses, creepers)
instead of stunning
player will get second buff, along side with slice and dice.
"Plan B"
for 4 seconds.
Effect - next attack (explossion included) is ignored, while player being knocked away.

... I might overcomplicated it this time.
It should be both simple, while improving vert poor survivability rating of rogue class...

Next text is also related to RPGseries modpack:
I found it difficult to deal with knifes and their range.
And so, first solution was spear.
Long range improved survivability by dozen.
However, then I decided to try and use knife with shield.
It appears to be excellent combo, as shield block prevents enemy attack for short period, so I could land 2-4 hits without getting hit.
This discovery leaded me to search for parry mod, and I found it.
https://www.curseforge.com/minecraft/mc-mods/sword-parry
It allows to parry attacks with any weapon.
Not only it made rogue playable as it should be,
but it also has parry cooldown that scales down with higher attack speed, which makes parry mechanic rogue related.
Other classes can parry too, but not as consistent, as it does rogue build.

That gave me another concept yesterday:
Channel skill for 2 seconds. After 2 seconds or interruption without activation skill goes on cooldown of 3 seconds with no effect.
Next incoming attack will activate skill and finish channel immediatly:
- incoming damage parried (ignored)
- attacker takes damage and stunned for 2 seconds
(damage should be more effective with fast weapons)
- projectile bounces aside
(attacker isn't affected when using ranged attack)

The only flaw of this concept are bosses and creepers.
Though, if "plan B" mechanic is possible, then it might be fine.
Though, could be simple speed boost...

What else could rise survivability of rogue build, except use of long attack range weapons, shields and mods?
(Perhaps, that parry mod is something that really worth of being included in modpack... but it has a few flaws that I'll explain in issue to that modpack.)

**Comment by ZsoltMolnarrr** [comment]
Sorry this is non actionable as a GitHub issue.

I recommend discussing this kind of topics on Discord, where the community is focusing on such topics.
