### ISSUE TITLE
[Forge] Skill books not working and disappearing

### ISSUE THREAD

**Issue by ColderonM27** [ZsoltMolnarrr/Rogues#7]
I use all of your rpg mods and syntra along with a few friends but so far only I am having this issue (I am also the only person using rogue but not warrior) where while skill book for rogue is equipped the prompts don't show on the hud and when leaving and re-entering the server my skill book gets deleted and sometimes equipped jewelry from the other mod does as well.

**Comment by ZsoltMolnarrr** [comment]
Unable to reproduce, most likely some issue with Trinkets.

Non-actionable for me. Sorry.
