### ISSUE TITLE
Crash with Armor Statues

### ISSUE THREAD

**Issue by lanwoodall423** [ZsoltMolnarrr/Rogues#9]
Not sure if this is an AzureLib, Rogues, or Armor Statues problem based on the log. 

I tried to place Warrior Leggings on an armor stand and got this crash. I have many other modded armors on armor stands and haven't had this issue.

[crash-2024-07-30_09.46.36-client.txt](https://github.com/user-attachments/files/16429078/crash-2024-07-30_09.46.36-client.txt)

This crash now occurs when rejoining the world 

[crash-2024-07-30_09.51.18-client.txt](https://github.com/user-attachments/files/16429086/crash-2024-07-30_09.51.18-client.txt)

**Comment by Partonetrain** [comment]
Does this happen without FancyDyes?

**Comment by ZsoltMolnarrr** [comment]
As the brochure images show, the custom armor models do work on armor stands.

The crash you experience is not caused by this mod, but instead by something that conflicts with AzureLib Armor.
